# Help with the git pipeline format from Texas Votes https://gitlab.com/forbesye/fitsbits/-/blob/master/.gitlab-ci.yml

image: node:latest
image: 
    name: postman/newman:alpine
    entrypoint: [""]

variables:
  POSTMAN_COLLECTION: https://api.getpostman.com/collections/23508831-8772309a-58f6-47aa-a9f5-b0d8da2ec0e5?apikey=PMAK-6359cc7672cca955b05f5c3c-0f91a95a1798852bb48a07cb5512dfadd0

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

cache:
  paths:
    - front-end/node_modules/

build_front_end:
  stage: build
  script:
    - cd front-end
    - npm install
    - CI=false npm run-script build

test_front_end:
  stage: test
  script:
    - make front-end-tests

test_back_end:
  image: python:3.6-stretch
  stage: test
  before_script:
    - python3 -m pip install --upgrade pip
    - pip3 install -r back-end/requirements.txt
  script:
    - make back-end-tests

test_postman:
  stage: test
  image: postman/newman:alpine
  script:
    - newman run ${POSTMAN_COLLECTION}