# Help with the git pipeline format from Texas Votes https://gitlab.com/forbesye/fitsbits/-/blob/master/.gitlab-ci.yml

image: node:latest

stages:
  -build

cache:
  paths:
    - front-end/node_modules/

build:
  stage: build
  script:
    - cd front-end
    - npm install
    - CI=false npm run-script build