# Help with the git pipeline format from Texas Votes https://gitlab.com/forbesye/fitsbits/-/blob/master/.gitlab-ci.yml
image: node:latest

stages:          # List of stages for jobs, and their order of execution
  - build

cache:
  paths:
    - front-end/node_modules/

build:
  stage: build
  script:
    - cd front-end
    - npm install
    - CI=false npm run-script build